### ISSUE TITLE
Curious behaviour

### ISSUE THREAD

**Issue by rob-deans** [rob-deans/robotics-cw#4]

**Comment by liam-grace** [comment]
Robot will search for any object that is blue. Upon finding it, it will circle the object

**Comment by EduardasV** [comment]
https://github.com/cosjac/Robotics-Coursework/tree/master/Coursework

**Comment by liam-grace** [comment]
Follow a maze until it finds blue using right wall follow https://en.wikipedia.org/wiki/Maze_solving_algorithm#Wall_follower
